services:
  - type: web
    name: interview-scheduler
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build
    startCommand: node server/scripts/seedRecruiter.js && node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_SQLITE
        value: "true"
      - key: SQLITE_STORAGE_PATH
        value: /tmp/scheduler.sqlite
      - key: CLIENT_URL
        value: "https://interview-scheduler-njl7.onrender.com"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: kavin.admin@gmail.com
      - key: ADMIN_PASSWORD
        value: 123
      - key: ADMIN_NAME
        value: Administrator
